/* Configuração: altere apenas estes valores para apontar para seu Worker.
 * O Worker deve expor GET /api/load, POST /api/demands, POST /api/log e POST /api/transfer.
 * GitHub (opcional no Worker): owner, repo e paths ficam aqui para referência.
 */
const CONFIG = Object.freeze({
    workerUrl: "github-api",
    github: { owner: "MarquesiasoTerceiro", repo: "gestao-demandas-app", demandsPath: "demandas.json", auditPath: "log.json" },
  requestTimeout: 9000
});
const USERS = [
  { id: "miguel-marques", name: "Miguel Marques", role: "Administrador", admin: true, developer: true },
  { id: "guilherme-pardo", name: "Guilherme Pardo", role: "Desenvolvedor", admin: false, developer: true },
  { id: "gabriel-maciel", name: "Gabriel Maciel", role: "Desenvolvedor", admin: false, developer: true },
  { id: "thaise-molon", name: "Thaise Molon", role: "Administrador", admin: true },
  { id: "quarto-desenvolvedor", name: "Quarto Desenvolvedor", role: "Desenvolvedor", admin: false, developer: true }
];
const DEMO_DEMANDS = [
  { id: "d-101", type: "Supply", title: "Consolidar indicadores de ruptura", focalPoint: "ana", details: "Atualizar painel semanal.", reason: "Atualizar painel semanal.", area: "Supply", priority: "high", status: "in_progress", assignee: "ana", createdBy: "ana", updatedAt: "2026-09-24T14:00:00Z" },
  { id: "d-102", type: "Comercial", title: "Revisar política de descontos", focalPoint: "bruno", details: "Validar regras com comercial.", reason: "Validar regras com comercial.", area: "Comercial", priority: "medium", status: "backlog", assignee: "bruno", createdBy: "bruno", updatedAt: "2026-09-23T11:00:00Z" },
  { id: "d-103", type: "Financeiro", title: "Acesso ao relatório de margem", focalPoint: "carla", details: "", reason: "Acesso ao relatório de margem", area: "Financeiro", priority: "low", status: "done", assignee: "carla", createdBy: "carla", updatedAt: "2026-09-20T16:30:00Z" }
];
const STATUS = { not_started: "Não Iniciado", development: "Em Desenvolvimento", paused: "Pausado", blocked_ti: "Bloqueado TI", blocked_adm: "Bloqueado ADM", validation: "Em Validação", done: "Concluído", cancelled: "Cancelado" };
const PRIORITY = Object.fromEntries(["P0", "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "X"].map((priority) => [priority, priority === "X" ? "X (sem prioridade)" : priority]));
const LEGACY_PRIORITY = { high: "P0", medium: "P1", low: "P2" };
const TYPES = ["Novo", "Correção", "Atualização", "Melhoria"];
const REASONS = ["Ajuste na Consulta SQL (CTEs, joins, CASEs, parâmetros etc.)", "Problema na Fonte de Dados do Databricks View ou Tabela", "Perda de Acesso à Fonte de Dados Databricks", "Problema de Credenciais no Databricks (Token)", "Problema na Fonte de Dados da Base Manual do Ponto Focal", "Perda de Acesso à Fonte de Dados da Base Manual do Ponto Focal", "Alteração na Regra de Negócio da Base Manual do Ponto Focal", "Problema na Fonte de Dados da Equipe BI (Base Manual)", "Alteração na Regra de Negócio da Base Manual da Equipe BI", "Ajuste na Consulta API (DAX Studio, Colunas, Filtros etc.)", "Problema na Fonte de Dados API", "Perda de Acesso à Fonte de Dados API", "Alteração na Regra de Negócio da Fonte de Dados API", "Problema na Fonte de Dados Macro", "Perda de Acesso à Fonte de Dados Macro (Acesso a Transações)", "Alteração na Regra de Negócio da Fonte de Dados Macro", "Ajuste de Visualização (Gráficos, Filtros, Interações etc.)", "Problema de Credenciais no Power BI Service (Web)", "Alteração na Regra de Negócio no Visual do Power BI", "Sem Acesso à Fonte de Dados Databricks", "Sem Acesso à Fonte de Dados da Base Manual do Ponto Focal", "Sem Acesso à Macro", "Sem Acesso à Fonte de Dados API"];
const STATUS_ALIASES = { backlog: "not_started", in_progress: "development", blocked: "blocked_ti" };
let state = { user: null, demands: [], audit: [], charts: {}, shas: { demands: null, log: null }, adminAll: true };
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]));
const currentUser = () => USERS.find((user) => user.id === state.user);
const normalizeName = (value) => value.trim().toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
const workerConfigured = () => Boolean(CONFIG.workerUrl && !CONFIG.workerUrl.includes("seu-worker"));
function showNotice(message, type = "error") { const el = $("#notice"); el.textContent = message; el.className = `notice ${type === "success" ? "success" : ""}`; el.hidden = false; setTimeout(() => { el.hidden = true; }, 6000); }
async function api(path, options = {}) {
  if (!CONFIG.workerUrl || CONFIG.workerUrl.includes("seu-worker")) throw new Error("Configure a URL do Cloudflare Worker em demandas/app.js.");
  const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), CONFIG.requestTimeout);
  try { const response = await fetch(`${CONFIG.workerUrl.replace(/\/$/, "")}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) }, signal: controller.signal }); const body = response.status === 204 ? null : await response.json().catch(() => null); if (!response.ok) { const error = new Error(body?.error || `Worker respondeu ${response.status}.`); error.status = response.status; error.body = body; throw error; } return body; } catch (error) { if (error.name === "AbortError") throw new Error("Tempo esgotado ao comunicar com o Worker."); throw error; } finally { clearTimeout(timeout); }
}
function normalizeDemand(d) { const activityId = d.activityId || d.id || d._id; const status = STATUS_ALIASES[d.status] || d.status || "not_started"; const developer = d.developer || d.assignee || d.focalPoint || ""; const priority = LEGACY_PRIORITY[d.priority] || d.priority; return { ...d, activityId, id: activityId, category: d.category || d.categoria || d.area || "", area: d.area || d.category || d.type || "", developer, assignee: developer, focalPoint: d.focalPoint || d.businessOwner || "", businessOwner: d.businessOwner || d.focalPoint || "", description: d.description ?? d.details ?? d.reason ?? "", possuiForms: d.possuiForms === "Sim" ? "Sim" : "Não", priority: PRIORITY[priority] ? priority : "X", status, updatedAt: d.updatedAt || d.updated_at || d.createdAt || new Date().toISOString(), createdBy: d.createdBy || d.created_by || d.actor || "" }; }
function visibleDemands() { const user = currentUser(); const owner = (value) => String(value || "").toLowerCase() === user.id.toLowerCase() || String(value || "").toLowerCase() === user.name.toLowerCase(); return state.demands.filter((d) => user.admin ? state.adminAll || owner(d.createdBy) : owner(d.createdBy) || owner(d.developer)); }
function logEntry(action, demandId, detail, demand) { return { action, demandId, detail, actor: currentUser().id, possuiForms: demand?.possuiForms === "Sim" ? "Sim" : "Não", at: new Date().toISOString() }; }
async function postLog(entry) { if (!workerConfigured()) { state.audit.unshift(entry); persistCache(); return; } const result = await api("/api/log", { method: "POST", body: JSON.stringify({ entry, expectedSha: state.shas.log }) }); state.shas.log = result?.version || state.shas.log; state.audit.unshift(result?.entry || entry); persistCache(); }
async function reloadAfterConflict() { showNotice("Conflito de versão detectado. Recarregando dados mais recentes…", "error"); await loadData(); }
async function loadData() {
  try { const data = await api("/api/load"); const payload = data?.data || data; const versions = payload.versions || {}; state.demands = (payload.demandas || []).map(normalizeDemand); state.audit = payload.log || []; state.shas.demands = versions.demandas || state.shas.demands; state.shas.log = versions.log || state.shas.log; showNotice("Dados sincronizados com o Worker.", "success"); }
  catch (error) { const cached = JSON.parse(localStorage.getItem("demandas-cache") || "null"); state.demands = ((Array.isArray(cached) ? cached : cached?.demands) || DEMO_DEMANDS).map(normalizeDemand); state.audit = Array.isArray(cached?.audit) ? cached.audit : []; if (cached?.shas) state.shas = cached.shas; showNotice(`Não foi possível carregar o Worker: ${error.message} Exibindo dados locais.`, "error"); }
  render();
}
function persistCache() { localStorage.setItem("demandas-cache", JSON.stringify({ demands: state.demands, audit: state.audit, shas: state.shas })); }
function render() { renderMetrics(); renderRecent(); renderTable(); renderAudit(); updateUserUi(); }
function renderMetrics() { const demands = visibleDemands(); const counts = Object.keys(STATUS).map((status) => demands.filter((d) => d.status === status).length); $("#metrics").innerHTML = `<div class="metric"><span class="eyebrow">Total</span><strong>${demands.length}</strong><small>visíveis para você</small></div><div class="metric"><span class="eyebrow">Em desenvolvimento</span><strong>${counts[1]}</strong><small>em execução agora</small></div><div class="metric"><span class="eyebrow">Não iniciado</span><strong>${counts[0]}</strong><small>aguardando início</small></div><div class="metric"><span class="eyebrow">Concluídas</span><strong>${counts[6]}</strong><small>entregas realizadas</small></div>`; }
const ACTIONS = [["start", "Iniciar / Retomar", ["not_started", "paused"] , "development"], ["pause", "Pausar", ["development", "validation"], "paused"], ["validate", "Validar", ["development"], "validation"], ["complete", "Concluir", ["validation", "development"], "done"], ["cancel", "Cancelar", ["not_started", "development", "paused", "validation"], "cancelled"], ["block_ti", "Bloquear TI", ["development", "validation"], "blocked_ti"], ["block_adm", "Bloquear ADM", ["development", "validation"], "blocked_adm"]];
function actionButtons(d) { return ACTIONS.filter(([, , allowed]) => allowed.includes(d.status)).map(([action, label, , target]) => `<button class="tiny-btn action-btn" data-action="status-action" data-status="${target}" data-id="${d.activityId}" data-confirm="${["complete", "cancel", "block_ti", "block_adm"].includes(action)}">${label}</button>`).join(""); }
function priorityRank(priority) { return priority === "X" ? Number.MAX_SAFE_INTEGER : Number(String(priority).replace("P", "")); }
function demandRow(d, compact = false) { const developer = USERS.find((u) => u.id === d.developer); return compact ? `<div class="demand-row"><div><strong>${esc(d.title)}</strong><div class="subtle">${esc(d.priority)} · ${esc(d.type || "")} · ${esc(developer?.name || d.developer || "Não atribuído")} · ${esc(d.businessOwner || "Negócio não informado")}</div></div><span class="status status-${d.status}">${STATUS[d.status] || d.status}</span><span class="subtle">${formatDate(d.updatedAt)}</span></div>` : `<tr><td>${esc(d.title)}<div class="subtle">${esc(d.details || d.description || "Sem descrição")}</div></td><td><strong>${esc(d.priority)}</strong></td><td>${esc(d.type || d.area)}</td><td>${esc(d.previsao || "—")}</td><td><span class="status status-${d.status}">${STATUS[d.status] || d.status}</span><div class="action-buttons">${actionButtons(d)}</div></td><td>${esc(developer?.name || d.developer || "Não atribuído")}<div class="subtle">Negócio: ${esc(d.businessOwner || "Não informado")}</div>${currentUser().admin ? `<button class="tiny-btn" data-action="transfer" data-id="${d.activityId}" title="Transferir">↔</button>` : ""}</td><td>${formatDate(d.updatedAt)}</td><td><button class="tiny-btn" data-action="details" data-id="${d.activityId}">Abrir</button></td></tr>`; }
function optionList(values, selected) { return values.map(([value, label]) => `<option value="${esc(value)}"${value === selected ? " selected" : ""}>${esc(label)}</option>`).join(""); }
function dashboardRow(d) { const developerOptions = USERS.filter((user) => user.developer); const statusOptions = Object.entries(STATUS); return `<tr data-id="${esc(d.activityId)}"><td class="id-cell">${esc(d.activityId)}</td><td><input class="grid-input" data-field="category" value="${esc(d.category)}" placeholder="Categoria" aria-label="Categoria"></td><td><select class="grid-input compact-select" data-field="type" aria-label="Tipo">${optionList(TYPES.map((type) => [type, type]), d.type)}</select></td><td><input class="grid-input title-input" data-field="title" value="${esc(d.title)}" maxlength="120" aria-label="Título"></td><td><input class="grid-input" data-field="businessOwner" value="${esc(d.businessOwner)}" placeholder="Ponto focal" aria-label="Ponto focal"></td><td><select class="grid-input compact-select" data-field="developer" aria-label="Desenvolvedor">${optionList(developerOptions.map((user) => [user.id, user.name]), d.developer)}</select></td><td><select class="grid-input compact-select priority-picker" data-field="priority" aria-label="Prioridade">${optionList(Object.entries(PRIORITY), d.priority)}</select></td><td><select class="grid-input compact-select status-picker" data-field="status" aria-label="Status">${optionList(statusOptions, d.status)}</select></td><td><button class="tiny-btn save-demand-btn" data-action="save-demand" data-id="${esc(d.activityId)}">Salvar</button></td></tr>`; }
function renderRecent() { const rows = visibleDemands().slice().sort((a, b) => priorityRank(a.priority) - priorityRank(b.priority) || new Date(b.updatedAt) - new Date(a.updatedAt)).map(dashboardRow).join(""); $("#recentList").innerHTML = rows; $("#dashboardEmpty").hidden = Boolean(rows); }
function renderTable() { const query = ($("#searchInput")?.value || "").toLowerCase(); const status = $("#statusFilter")?.value || ""; const priority = $("#priorityFilter")?.value || ""; const rows = visibleDemands().filter((d) => (!query || `${d.title} ${d.area} ${d.description}`.toLowerCase().includes(query)) && (!status || d.status === status) && (!priority || d.priority === priority)).sort((a, b) => priorityRank(a.priority) - priorityRank(b.priority)); $("#demandTable").innerHTML = rows.map((d) => demandRow(d)).join(""); $("#emptyState").hidden = rows.length > 0; }
function renderAudit() { $("#auditList").innerHTML = state.audit.length ? state.audit.slice(0, 30).map((item) => `<div class="audit-item"><time>${formatDate(item.at || item.createdAt)}</time><div><strong>${esc(item.action || "Atualização")}</strong><div class="subtle">${esc(item.detail || item.message || "")} · Possui Forms: <strong>${esc(item.possuiForms || "Não")}</strong></div></div></div>`).join("") : '<div class="empty">O Worker ainda não retornou eventos de auditoria.</div>'; }
function renderCharts() {
  if (!window.Chart) {
    document.querySelectorAll(".chart-fallback").forEach((x) => { x.hidden = false; });
    return;
  }
  const demands = visibleDemands();
  const statusData = Object.keys(STATUS).map((key) => demands.filter((d) => d.status === key).length);
  const priorityData = Object.keys(PRIORITY).map((key) => demands.filter((d) => d.priority === key).length);
  [["statusChart", "status", Object.values(STATUS), statusData, ["#b8c3cd", "#efa968", "#e57d89", "#42bca3"]], ["priorityChart", "priority", Object.values(PRIORITY), priorityData, ["#e57d89", "#efa968", "#63aaba"]]].forEach(([id, key, labels, data, colors]) => {
    if (state.charts[key]) state.charts[key].destroy();
    state.charts[key] = new Chart($(`#${id}`), {
      type: key === "status" ? "bar" : "doughnut",
      data: { labels, datasets: [{ data, backgroundColor: colors, borderWidth: 0, borderRadius: 5 }] },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: key !== "status", position: "bottom", labels: { usePointStyle: true, padding: 16 } } },
        scales: key === "status" ? { y: { beginAtZero: true, ticks: { stepSize: 1 } }, x: { grid: { display: false } } } : {}
      }
    });
  });
}
function updateUserUi() { const user = currentUser(); if (!user) return; $("#welcomeText").textContent = `Bem vindo ${user.name}`; $("#roleBadge").textContent = user.admin ? "Administrador" : "Desenvolvedor"; document.querySelectorAll(".admin-only").forEach((el) => { el.hidden = !user.admin; }); let toggle = $("#adminScopeToggle"); if (user.admin && !toggle) { toggle = document.createElement("label"); toggle.id = "adminScopeToggle"; toggle.innerHTML = '<input type="checkbox" checked> Ver todas'; toggle.style.cssText = "font-size:11px;font-weight:600;display:flex;align-items:center;gap:4px"; $(".user-controls").append(toggle); toggle.querySelector("input").onchange = (e) => { state.adminAll = e.target.checked; render(); }; } if (toggle) toggle.hidden = !user.admin; $("#reasonSelect").innerHTML = `<option value="">Selecione o motivo</option>${REASONS.map((reason) => `<option>${esc(reason)}</option>`).join("")}`; $("#statusFilter").innerHTML = `<option value="">Todos os status</option>${Object.entries(STATUS).map(([key, value]) => `<option value="${key}">${value}</option>`).join("")}`; }
function formatDate(value) { return value ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(value)).replace(".", "") : "—"; }
async function createDemand(form) { const reason = form.reason.value; if (form.type.value === "Correção" && !reason) { showNotice("Motivo é obrigatório para Correção."); return; } const user = currentUser(); const demand = normalizeDemand({ activityId: `d-${Date.now()}`, category: form.category.value.trim(), type: form.type.value, priority: form.priority.value || "X", title: form.title.value.trim(), previsao: Number(form.previsao.value), developer: user.id, assignee: user.id, focalPoint: form.businessOwner.value.trim(), businessOwner: form.businessOwner.value.trim(), possuiForms: form.possuiForms.value, details: form.details.value.trim(), reason: form.type.value === "Correção" ? reason : "", status: "not_started", createdBy: user.id, updatedAt: new Date().toISOString() }); try { let saved = demand; if (workerConfigured()) { const result = await api("/api/demands", { method: "POST", body: JSON.stringify({ demand, expectedSha: state.shas.demands, actor: user.id }) }); saved = normalizeDemand(result?.demand || demand); state.shas.demands = result?.version || state.shas.demands; } state.demands.unshift(saved); await postLog(logEntry("created", saved.activityId, `Demanda criada: ${saved.title}`, saved)); persistCache(); showNotice(workerConfigured() ? "Demanda criada e registrada." : "Demanda criada localmente e registrada no log.", "success"); resetDemandForm(form); render(); } catch (error) { if (error.status === 409) return reloadAfterConflict(); showNotice(`Não foi possível salvar: ${error.message}`, "error"); } }
async function saveDemandFromRow(row) { const demand = state.demands.find((item) => item.activityId === row.dataset.id); if (!demand) return; const previous = { ...demand }; row.querySelectorAll("[data-field]").forEach((field) => { demand[field.dataset.field] = field.value.trim ? field.value.trim() : field.value; }); demand.area = demand.category || demand.area || demand.type; demand.assignee = demand.developer; demand.updatedAt = new Date().toISOString(); try { if (workerConfigured()) { const result = await api("/api/demands", { method: "POST", body: JSON.stringify({ demand, expectedSha: state.shas.demands, actor: currentUser().id }) }); Object.assign(demand, normalizeDemand(result?.demand || demand)); state.shas.demands = result?.version || state.shas.demands; } await postLog(logEntry("updated", demand.activityId, `Demanda atualizada: ${demand.title}`, demand)); persistCache(); render(); showNotice(workerConfigured() ? "Demanda atualizada." : "Demanda atualizada localmente e registrada no log.", "success"); } catch (error) { Object.assign(demand, previous); if (error.status === 409) return reloadAfterConflict(); showNotice(`Não foi possível atualizar: ${error.message}`, "error"); } }
function resetDemandForm(form = $("#demandForm")) { form.reset(); updateReasonField(); if ($("#demandDialog").open) $("#demandDialog").close(); }
async function updateStatus(id, status) { const demand = state.demands.find((d) => d.activityId === id); if (!demand) return; const previous = demand.status; demand.status = status; demand.updatedAt = new Date().toISOString(); try { if (workerConfigured()) { const result = await api("/api/demands", { method: "POST", body: JSON.stringify({ demand: { ...demand, activityId: id, status }, expectedSha: state.shas.demands, actor: currentUser().id }) }); Object.assign(demand, normalizeDemand(result?.demand || demand)); state.shas.demands = result?.version || state.shas.demands; } await postLog(logEntry("status_updated", id, `${STATUS[previous]} → ${STATUS[status]}`, demand)); showNotice(workerConfigured() ? "Status atualizado." : "Status atualizado localmente e registrado no log.", "success"); } catch (error) { demand.status = previous; if (error.status === 409) return reloadAfterConflict(); showNotice(`Não foi possível atualizar: ${error.message}`, "error"); } persistCache(); render(); }
async function transferDemand(id) { if (!currentUser().admin) return; const demand = state.demands.find((d) => d.activityId === id); const options = USERS.filter((user) => user.developer).map((user) => `${user.id} (${user.name})`).join(", "); const assignee = window.prompt(`Informe o ID do novo desenvolvedor: ${options}`, demand?.developer || ""); if (!assignee || !USERS.some((user) => user.id === assignee && user.developer) || !demand) { if (assignee) showNotice("Desenvolvedor inválido. Use um dos IDs exibidos.", "error"); return; } const previous = demand.developer; demand.developer = assignee; demand.assignee = assignee; try { const result = await api("/api/transfer", { method: "POST", body: JSON.stringify({ activityId: id, destination: assignee, expectedDemandSha: state.shas.demands, expectedLogSha: state.shas.log, entry: logEntry("transferred", id, `Transferida para ${assignee}`, demand) }) }); state.shas.demands = result?.versions?.demandas || state.shas.demands; state.shas.log = result?.versions?.log || state.shas.log; showNotice("Demanda transferida.", "success"); } catch (error) { demand.developer = previous; demand.assignee = previous; if (error.status === 409) return reloadAfterConflict(); showNotice(`Não foi possível transferir: ${error.message}`, "error"); } persistCache(); render(); }
function exportCsv() { const header = ["activity_id", "categoria", "tipo", "titulo", "ponto_focal", "desenvolvedor", "prioridade", "status", "previsao", "possui_forms", "atualizada"]; const rows = visibleDemands().sort((a, b) => priorityRank(a.priority) - priorityRank(b.priority)).map((d) => [d.activityId, d.category, d.type || d.area, d.title, d.businessOwner || "", USERS.find((u) => u.id === d.developer)?.name || d.developer || "", d.priority, STATUS[d.status], d.previsao, d.possuiForms, d.updatedAt]); const csv = [header, ...rows].map((row) => row.map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`).join(";")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" })); link.download = `demandas-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); }
function updateReasonField() { const correction = $("#demandForm").type.value === "Correção"; const wrap = $("#reasonWrap"); const select = $("#reasonSelect"); wrap.classList.toggle("is-correction", correction); select.disabled = !correction; select.required = correction; if (!correction) select.value = ""; }
function setView(view) { document.querySelectorAll(".view").forEach((el) => { el.hidden = el.id !== `${view}View`; }); document.querySelectorAll(".nav-link").forEach((el) => el.classList.toggle("active", el.dataset.view === view)); $("#viewTitle").textContent = view === "dashboard" ? "Visão geral" : view === "demands" ? "Todas as demandas" : "Auditoria"; }
function init() { $("#dateLabel").textContent = new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "numeric", month: "long" }).format(new Date()); $("#loginForm").onsubmit = (event) => { event.preventDefault(); const form = event.currentTarget; const fullName = `${normalizeName(form.firstName.value)} ${normalizeName(form.lastName.value)}`; const user = USERS.find((candidate) => normalizeName(candidate.name) === fullName); if (!user || form.password.value !== "12345678") { $("#loginError").textContent = "Nome, sobrenome ou senha inválidos."; $("#loginError").hidden = false; return; } state.user = user.id; $("#loginError").hidden = true; $("#loginScreen").hidden = true; $("#loginScreen").style.display = "none"; $("#loginScreen").setAttribute("aria-hidden", "true"); $(".app-shell").style.display = "flex"; updateUserUi(); updateReasonField(); loadData(); }; $("#logoutBtn").onclick = () => { state.user = null; $("#demandForm").reset(); $("#demandDialog").close(); $(".app-shell").style.display = "none"; $("#loginForm").reset(); $("#loginError").hidden = true; $("#loginScreen").style.display = ""; $("#loginScreen").hidden = false; $("#loginScreen").removeAttribute("aria-hidden"); $("#loginForm").firstName.focus(); }; document.querySelectorAll("[data-view]").forEach((el) => el.onclick = () => setView(el.dataset.view)); ["#newDemandBtn", "#newDemandBtn2"].forEach((id) => $(id).onclick = () => { resetDemandForm(); $("#demandDialog").showModal(); }); $("#closeDialog").onclick = $("#cancelDialog").onclick = () => resetDemandForm(); $("#demandForm").onsubmit = (e) => { e.preventDefault(); createDemand(e.target); }; $("#demandForm").type.onchange = updateReasonField; ["#searchInput", "#statusFilter", "#priorityFilter"].forEach((id) => $(id).oninput = renderTable); $("#exportBtn").onclick = () => exportCsv(visibleDemands()); const handleAction = (e) => { const button = e.target.closest("[data-action]"); if (button?.dataset.action === "details") showNotice("Detalhe disponível no registro da demanda.", "success"); if (button?.dataset.action === "transfer") transferDemand(button.dataset.id); if (button?.dataset.action === "save-demand") saveDemandFromRow(button.closest("tr")); if (button?.dataset.action === "status-action") { if (button.dataset.confirm === "true" && !window.confirm("Confirmar ação terminal/bloqueio?")) return; updateStatus(button.dataset.id, button.dataset.status); } }; $("#demandTable").onclick = handleAction; $("#recentList").onclick = handleAction; $("#configBtn").onclick = () => { $("#configText").innerHTML = `<strong>Worker URL:</strong> <code>${esc(CONFIG.workerUrl)}</code><br><strong>GitHub:</strong> ${esc(CONFIG.github.owner)}/${esc(CONFIG.github.repo)}<br><strong>Paths:</strong> ${esc(CONFIG.github.demandsPath)} / ${esc(CONFIG.github.auditPath)}<br><br>Edite <code>demandas/app.js</code> para configurar o ambiente.`; $("#configDialog").showModal(); }; }
document.addEventListener("DOMContentLoaded", init);
